### ISSUE TITLE
Serialization broken since 3.79.0

### ISSUE THREAD

**Issue by supermihi** [angularsen/UnitsNet#387]
The following does not run with UnitsNet-3.79.0 (introduction of `QuantityValue`) onwards, but did with previous versions:

```csharp
[Fact]
public void CanSerializeSpeedAndFuel()
{
    var saf = new SpeedFuel(Speed.FromKilometersPerHour(10), Volume.FromCubicCentimeters(10));
    var text = JsonConvert.SerializeObject(saf, Formatting.None, new UnitsNetJsonConverter());
    var parsed = JsonConvert.DeserializeObject<SpeedFuel>(text, new UnitsNetJsonConverter());
    Assert.Equal(10, parsed.Speed.KilometersPerHour, 10);
    Assert.Equal(10, parsed.FuelPerHour.CubicCentimeters, 10);
}

public struct SpeedFuel
{
    public SpeedFuel(Speed speed, Volume fuelPerHour)
    {
        Speed = speed;
        FuelPerHour = fuelPerHour;
    }

    public Speed Speed { get; }
    public Volume FuelPerHour { get; }
}
```

In the *deserialize* step, an `ArgumentException` is thrown:
```
System.ArgumentException
  HResult=0x80070057
  Message=Object of type 'System.Double' cannot be converted to type 'UnitsNet.QuantityValue'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at UnitsNet.Serialization.JsonNet.UnitsNetJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at SpeedAndFuelTests.CanSerializeSpeedAndFuel() in C:\SpeedAndFuelTests.cs:line 26
```

I am running .NET Core 2.0 with Newtonsoft.Json-10.0.3 and UnitsNet.Serialization.JsonNet-1.2.1 (also tried 1.2.0).

**Comment by angularsen** [comment]
Ouch. Thanks for reporting! cc @eriove @ferittuncer 

I've seen similar issues with Convert.ToDouble() in other scenarios with this type. Does anyone see a clear solution here?

I think possibly one way to fix this and still keep this type around (which was introduced to avoid method overload explosion for N number types) is to have it implement the `IConvertible` interface. This would require a jump from 1.0 to 1.3 (I think) in netstandard, but I don't think that is unreasonable.

**Comment by gojanpaolo** [comment]
Reflecting QuantityValue in UnitsNetJsonConverter.ReadJson seems to also do the trick.

something like:
```
public override object ReadJson(...)
{
	//...
	Type quantityValueType = Type.GetType("UnitsNet.QuantityValue,UnitsNet");
	var quantityValue =
#if (NETSTANDARD1_0)
		vu.Value;
#else
		quantityValueType
			.GetMethod("op_Implicit", new[] { typeof(double) }) //get implicit conversion from double to QuantityValue
			.Invoke(null, new object[] { vu.Value });
#endif
	return fromMethod.Invoke(null, new[] { quantityValue, unit });
}

```

**Comment by angularsen** [comment]
Thanks for the suggestion. I'm a little concerned this adds even more reflection magic that is prone to break at some point. I'll investigate if implementing `IConvertible` does the trick.

**Comment by angularsen** [comment]
Json nuget 1.2.2 with patch is now out, could you give it a try?

**Comment by supermihi** [comment]
Thanks, appears to work! 👍

**Comment by angularsen** [comment]
Awesome, thanks for testing.
