### ISSUE TITLE
Json serialization is broken in 4.7.0

### ISSUE THREAD

**Issue by dmytro-gokun** [angularsen/UnitsNet#598]
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'QuantityInfo' with type 'UnitsNet.QuantityInfo`1[UnitsNet.Units.SpeedUnit]'. Path 'Positions[0].Speed.QuantityInfo.Zero'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)

Now, I see that if I use ReferenceLoopHandling.Ignore in JsonSerializerSettings that solves the problem in the sense that no exception is more thrown. However, the Json i get is huge, with all possible properties from Speed. I'd only expect it to contain value and units instead. But, may be i'm doing it all wrong? Could someone point me to the correct sample/doc?

**Comment by dmytro-gokun** [comment]
Okay, looks like I should have read the docs before posting the question. 

In case anyone is interested, I should have referenced UnitsNet.Serialization.JsonNet and then added UnitsNetJsonConverter to JsonSerializerSettings:

settings.Converters.Add(new UnitsNetJsonConverter());

What have deceived me is that it worked w/o exceptions before 4.7.0 release. But it still produced bloated JSON before then, so I should have used UnitsNetJsonConverter anyway.

**Comment by angularsen** [comment]
Ah, yes I think in earlier 3.x versions it didn't work at all actually until we added the UnitsNetJsonConverter.
Thanks for the details and I'm glad you figured it out.
