### ISSUE TITLE
Using library to populate database

### ISSUE THREAD

**Issue by swidz** [angularsen/UnitsNet#946]
I would like to use this library to seed a database.
How to generate a list of all units of a particular type (i.e. Length, Duration, Mass)

I would like to get the following fields:
type, default abbreviation, name

Additionally I would like to seed translations:
name, localized abbreviation, localized name

I was trying the following but it throws errors as some abbreviations can be used by different units

```
            object[] lengthUnits = Length.Units.Skip(1).Cast<object>().ToArray();
            foreach (var lengthUnit in lengthUnits)
            {
                var abbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(lengthUnit.GetType(), (int)lengthUnit);
                var name = UnitParser.Default.Parse(abbreviation, lengthUnit.GetType());
                _logger.LogInformation($"{abbreviation} {name}");

            }

            object[] massUnits = Mass.Units.Skip(1).Cast<object>().ToArray();
            foreach (var massUnit in massUnits)
            {
                var abbreviation = UnitAbbreviationsCache.Default.GetDefaultAbbreviation(massUnit.GetType(), (int)massUnit);
                var name = UnitParser.Default.Parse(abbreviation, massUnit.GetType());
                _logger.LogInformation($"{abbreviation} {name}");

            }
```

UnitsNet.AmbiguousUnitParseException
  HResult=0x00000002
  Message=Cannot parse "pica" since it could be either of these: DtpPica, PrinterPica
  Source=UnitsNet
  StackTrace:
   at UnitsNet.UnitParser.Parse(String unitAbbreviation, Type unitType, IFormatProvider formatProvider)
   at Infovision.Planner.Persistence.PlannerDbSeeder.AddUnitOfMeasures() in C:\Users\Admin\source\repos\Infovision.Planner\src\Infovision.Planner.Persistence\PlannerDbSeeder.cs:line 75
   at Infovision.Planner.Persistence.PlannerDbSeeder.Initialize() in C:\Users\Admin\source\repos\Infovision.Planner\src\Infovision.Planner.Persistence\PlannerDbSeeder.cs:line 53
   at Infovision.Planner.WebAPI.Extensions.ApplicationBuilderExtensions.SeedApplicationDb(IApplicationBuilder app, IConfiguration configuration) in C:\Users\Admin\source\repos\Infovision.Planner\src\Infovision.Planner.WebAPI\Extensions\ApplicationBuilderExtensions.cs:line 74
   at Infovision.Planner.WebAPI.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IStringLocalizer`1 localizer) in C:\Users\Admin\source\repos\Infovision.Planner\src\Infovision.Planner.WebAPI\Startup.cs:line 141
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

**Comment by angularsen** [comment]
Take a look at how it enumerates quantities and their units and abbreviations:
https://github.com/angularsen/UnitsNet/tree/master/Samples/UnitConverter.Wpf

> I was trying the following but it throws errors as some abbreviations can be used by different units

Yes, a handful of unit abbreviations are ambiguous and you can't always expect to be able to `Parse` the result of a `ToString()`.

However, you should not have to use parse to achieve what you want.

> name, localized abbreviation, localized name

If by localized name you mean French translation of `Length` or `Centimeter` then those don't currently exist in the library. There has been issues asking for it earlier, but none have tried a pull request to add it.

Hope this helps!
